widgetTheme=widget-themes/oval
primaryColor=#ec008c
secondaryColor=#ec008c
labelColor=#ffffff
hideWhenOffline=false
contactMail=khemiri.ridha2013@gmail.com
loadingLabel=Chargement...
loginError=Erreur d'identification
chatHeader=Parlez-nous
startInfo=Remplissez le formulaire suivant pour commencer le chat
widgetWidth=337
widgetHeight=411
widgetOffset=80
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Commencer le chat
backLabel=Retour
initMessageBody=Bonjour, comment puis-je vous aider?
initMessageAuthor=Assistant
chatInputLabel=Écrivez votre question
timeDaysAgo=day(s) ago
timeHoursAgo=hour(s) ago
timeMinutesAgo=minute(s) ago
timeSecondsAgo=second(s) ago
offlineMessage=L'assistant n'est pas connecté
toggleSoundLabel=Effets sonores
toggleScrollLabel=Défilement automatique
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Basculer en plein écran
endChatLabel=Terminer le chat
endChatConfirmQuestion=Êtes-vous sûr?
endChatConfirm=Oui
endChatCancel=Annuler
contactHeader=Contactez nous
contactInfo=Tous les opérateurs sont hors ligne. Utilisez le formulaire ci-dessous pour nous envoyer un e-mail avec votre question.
contactNameLabel=Votre nom
contactMailLabel=Votre-mail
contactQuestionLabel=Écrivez votre question
contactSendLabel=Envoyer
contactSuccessHeader=Message envoyé
contactSuccessMessage=Votre question à été envoyée. Je vous remercie!
contactErrorHeader=Erreur
contactErrorMessage=Une erreur s'est produite lors de l'envoi de votre question
headerHeight=45
installed=1
autoShowWidgetAfter=10
autoShowWidget=false
askForMail=true
notificationIcon=img/notification.png
